<?php
  ob_start();
  session_start();
  
  include 'WebClientPrint.php';
  use Neodynamic\SDK\Web\WebClientPrint;
  
  $title = 'Detecting WebClientPrint Processor...';
  
  $style = '.glyphicon-refresh-animate {
    -animation: spin .7s infinite linear;
    -webkit-animation: spin2 .7s infinite linear;
}
@-webkit-keyframes spin2 {
    from { -webkit-transform: rotate(0deg);}
    to { -webkit-transform: rotate(360deg);}
}
@keyframes spin {
    from { transform: scale(1) rotate(0deg);}
    to { transform: scale(1) rotate(360deg);}
}';
  
  
?>

<input type="hidden" id="sid" name="sid" value="<?php echo session_id(); ?>" />

<div id="msgInProgress">
    <div id="mySpinner" style="width:32px;height:32px"></div>
    <br />
    <h3>Detecting WCPP utility at client side...</h3>
    <h3><span class="label label-info"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Please wait a few seconds...</span></h3>
    <br />
</div>
<div id="msgInstallWCPP" style="display:none;">
    <h3>#1 Install WebClientPrint Processor (WCPP)!</h3>
    <p>
        <strong>WCPP is a native app (without any dependencies!)</strong> that handles all print jobs
        generated by the <strong>WebClientPrint for PHP component</strong> at the server side. The WCPP
        is in charge of the whole printing process and can be
        installed on <strong>Windows, Linux, Mac & Raspberry Pi!</strong>
    </p>
    <p>
        <a href="//www.neodynamic.com/downloads/wcpp/" target="_blank" class="btn btn-warning" >Download and Install WCPP from Neodynamic website</a><br />
    </p>
    <h3>#2 After installing WCPP...</h3>
    <p>
        <a href="Samples.php" class="btn btn-info">You can go and test the printing page...</a>
    </p>

</div>


<?php
  $content = ob_get_contents();
  ob_clean();
?>


<script type="text/javascript">
    
        //var wcppPingDelay_ms = 5000; 
        
        var wcppPingTimeout_ms = 10000; //10 sec
        var wcppPingTimeoutStep_ms = 500; //0.5 sec

        function wcppDetectOnSuccess(){
            var wcppVer = arguments[0];
            if(wcppVer.substring(0, 1) == "4")
                window.location.href = "samples.php";
            else
                wcppDetectOnFailure();
        }

        function wcppDetectOnFailure() {
            $("#msgInProgress").hide();
            $("#msgInstallWCPP").show();                
        }

</script>


<?php
    
    //Get Absolute URL of this page
    $currentAbsoluteURL = (@$_SERVER["HTTPS"] == "on") ? "https://" : "http://";
    $currentAbsoluteURL .= $_SERVER["SERVER_NAME"];
    if($_SERVER["SERVER_PORT"] != "80" && $_SERVER["SERVER_PORT"] != "443")
    {
        $currentAbsoluteURL .= ":".$_SERVER["SERVER_PORT"];
    } 
    $currentAbsoluteURL .= $_SERVER["REQUEST_URI"];
    
    //WebClientPrinController.php is at the same page level as WebClientPrint.php
    $webClientPrintControllerAbsoluteURL = substr($currentAbsoluteURL, 0, strrpos($currentAbsoluteURL, '/')).'/WebClientPrintController.php';

    // Create WCPP detection script
    echo WebClientPrint::createWcppDetectionScript($webClientPrintControllerAbsoluteURL, session_id());
    
?>

<?php
  $script = ob_get_contents();
  ob_clean();
  
  include("template.php");
?>